---
- name: Install apt packages 
  become: true
  apt:
    name:
      # essential build tools (gcc, make, etc)
      - build-essential
      - libtool
      - python
      - python3
      - pkg-config
      - gcc-8
      - git

      # Needed for mounting recovery image
      - kpartx

      # Audio / CRAS dependencies
      - acpid
      - libudev-dev
      - libsbc-dev
      - libalsaplayer-dev
      - libiniparser-dev
      - ladspa-sdk
      - libspeex-dev
      - libspeexdsp-dev
      - libasound2-dev

    state: latest 
- name: Create /etc/libinput directory if it does not exist
  file:
    path: /etc/libinput
    state: directory
    mode: '0755'

- name: Change default compile to use gcc-8
  become: true
  command:
    cmd: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8
